"use strict";

viewModules.engineering="work-orders";
labels.engineering="Ерөнхий инженерийн удирдлага";
state.engineeringData=null;
state.engineeringLoading=false;
state.engineeringTab="overview";
state.engineeringPeriod=new Date().toISOString().slice(0,7);

const engineeringRenderBefore=render;
render=function(){if(state.view!=="engineering")return engineeringRenderBefore();renderEngineering()};

function engineeringPeriodParts(){const [year,month]=state.engineeringPeriod.split("-").map(Number);return{year,month}}
async function loadEngineering(force=false){
  if(state.engineeringLoading||state.engineeringData&&!force)return;
  state.engineeringLoading=true;render();
  try{const {year,month}=engineeringPeriodParts();state.engineeringData=await api(`/api/engineering/overview?year=${year}&month=${month}`)}
  catch(error){state.engineeringData={error:error.message||"Инженерийн мэдээлэл ачаалж чадсангүй."}}
  finally{state.engineeringLoading=false;if(state.view==="engineering")render()}
}
function engineeringProgress(item){
  const stages={awaiting_safety_start:10,awaiting_management_start:20,execution:50,awaiting_safety_completion:75,awaiting_management_completion:90,completed:100,cancelled:100};
  return stages[item.workflow_stage]??({new:5,assigned:20,in_progress:50,pending_review:80,completed:100,cancelled:100}[item.status]||0);
}
function engineeringOpen(item){return !["completed","cancelled"].includes(item.status)}
function engineeringOverdue(item){return engineeringOpen(item)&&item.due_at&&new Date(item.due_at)<new Date()}
function engineeringDomainStats(items,domain){const rows=items.filter(x=>x.engineering_domain===domain),open=rows.filter(engineeringOpen),done=rows.filter(x=>x.status==="completed"),overdue=rows.filter(engineeringOverdue),avg=rows.length?Math.round(rows.reduce((n,x)=>n+engineeringProgress(x),0)/rows.length):0;return{rows,total:rows.length,open:open.length,done:done.length,overdue:overdue.length,avg}}
function engineeringStage(item){const management=["awaiting_management_start","awaiting_management_completion"].includes(item.workflow_stage),done=item.status==="completed";return`<span class="engineering-stage ${management?"management":""} ${done?"done":""}">${esc(labels[item.workflow_stage]||labels[item.status]||item.workflow_stage||item.status||"—")}</span>`}
function engineeringActionLabel(action){return{management_approve_start:"Эхлүүлэх",management_close:"Хаах",management_return_to_execution:"Буцаах",safety_authorize_start:"ХАБЭА зөвшөөрөх",safety_accept_completion:"ХАБЭА хянах",safety_return_to_execution:"Буцаах",submit_completion:"Дуусгаж илгээх"}[action]||action}
function engineeringActions(item){const actions=item.available_actions||[];return`<div class="engineering-actions">${actions.map(action=>`<button class="${action.includes("return")?"secondary":"primary"}" data-workflow-id="${item.id}" data-workflow-action="${action}">${engineeringActionLabel(action)}</button>`).join("")}<button class="secondary" data-history-id="${item.id}">Түүх</button></div>`}
function engineeringTable(items){
  const rows=items.map(item=>{const progress=engineeringProgress(item);return`<tr><td><button class="work-link" data-history-id="${item.id}">${esc(item.title)}</button><small>${esc(item.work_type_name||item.category||"—")} · ${esc(item.asset_name||"Объектгүй")}</small></td><td>${esc(item.assigned_name||"Хариуцагчгүй")}</td><td class="${engineeringOverdue(item)?"overdue-text":""}">${item.due_at?dateTime(item.due_at):"—"}</td><td><div class="engineering-progress"><b>${progress}%</b><div><i style="width:${progress}%"></i></div></div></td><td><div class="engineering-proof"><span>Түүх ${Number(item.evidence_event_count||0)}</span><span>Файл ${Number(item.attachment_count||0)}</span>${Number(item.scope_count||0)?`<span>Хамрах хүрээ ${item.scope_count}</span>`:""}${Number(item.material_request_count||0)?`<span>Материал ${item.material_request_count}</span>`:""}</div></td><td>${engineeringStage(item)}</td><td>${engineeringActions(item)}</td></tr>`}).join("");
  return`<div class="engineering-table-wrap"><table class="engineering-table"><thead><tr><th>Ажил / объект</th><th>Хариуцагч</th><th>Дуусгах хугацаа</th><th>Явц</th><th>Нотолгоо, нөөц</th><th>Үе шат</th><th>Үйлдэл</th></tr></thead><tbody>${rows||`<tr><td colspan="7"><div class="engineering-empty">Энэ хэсэгт ажил алга.</div></td></tr>`}</tbody></table></div>`;
}
function engineeringKpi(label,value,note,tone){return`<article class="engineering-kpi" style="--tone:${tone}"><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`}
function engineeringDomainCard(label,stats,tab){return`<article class="engineering-domain"><header><div><small>ҮЙЛ АЖИЛЛАГААНЫ ЧИГЛЭЛ</small><h3>${label}</h3></div><b>${stats.total}</b></header><div class="engineering-domain-metrics"><span><b>${stats.open}</b>Нээлттэй</span><span><b>${stats.done}</b>Хаагдсан</span><span><b>${stats.overdue}</b>Хоцорсон</span><span><b>${stats.avg}%</b>Дундаж явц</span></div><button class="secondary" data-engineering-tab="${tab}" style="margin-top:12px">Дэлгэрэнгүй →</button></article>`}
function engineeringAttention(items){
  const alerts=[];
  for(const item of items){if(!engineeringOpen(item))continue;if(!item.assigned_to)alerts.push({item,type:"Хариуцагчгүй",color:"#d69a00"});if(engineeringOverdue(item))alerts.push({item,type:"Хугацаа хэтэрсэн",color:"#d92d20"});if(["awaiting_management_start","awaiting_management_completion"].includes(item.workflow_stage))alerts.push({item,type:"Инженерийн шийдвэр",color:"#1763d6"});if(Number(item.material_pending_count)>0)alerts.push({item,type:"Материал хүлээж байна",color:"#7a5af8"})}
  return alerts.sort((a,b)=>Number(engineeringOverdue(b.item))-Number(engineeringOverdue(a.item))).slice(0,12).map(x=>`<button class="engineering-alert" style="--alert:${x.color}" data-history-id="${x.item.id}"><span><strong>${esc(x.item.title)}</strong><small>${esc(x.item.assigned_name||"Хариуцагчгүй")} · ${x.item.due_at?dateTime(x.item.due_at):"хугацаагүй"}</small></span><b>${x.type}</b></button>`).join("")||'<div class="engineering-empty">Шуурхай анхаарах ажил алга.</div>';
}
function engineeringReport(data){const r=data.review||{},p=data.period;return`<form class="panel" id="engineeringReviewForm"><div class="panel-head"><div><span class="panel-kicker">САРЫН УДИРДЛАГЫН ТЭМДЭГЛЭЛ</span><h2>${p.year} оны ${p.month}-р сар</h2></div><button class="primary" ${data.capabilities.canReview?"":"disabled"}>Дүгнэлт хадгалах</button></div><div class="engineering-report"><div><label>Сарын ерөнхий дүгнэлт<textarea class="input" name="summaryNote" rows="4" placeholder="Гол үр дүн, ажлын явцыг товч дүгнэнэ.">${esc(r.summary_note||"")}</textarea></label><label>Саатал, асуудал<textarea class="input" name="issueNote" rows="4" placeholder="Материал, хүн хүч, техник, ХАБЭА, цаг агаарын саатал.">${esc(r.issue_note||"")}</textarea></label><label>Нөөц, материал, техникийн хэрэгцээ<textarea class="input" name="resourceNote" rows="4">${esc(r.resource_note||"")}</textarea></label></div><div><label>Дараа сарын чиглэл<textarea class="input" name="nextPlanNote" rows="5" placeholder="Шилжих болон түрүүлж хийх ажлууд.">${esc(r.next_plan_note||"")}</textarea></label><label>Удирдлагад өгөх эцсийн дүгнэлт<textarea class="input" name="conclusionNote" rows="5">${esc(r.conclusion_note||"")}</textarea></label><p class="engineering-report-meta">Тоон үзүүлэлт Work Order-оос автоматаар гарна. Энд зөвхөн инженерийн тайлбар, шалтгаан, шийдвэрийн санал хадгалагдана.${r.updated_by_name?`<br>Сүүлд шинэчилсэн: ${esc(r.updated_by_name)} · ${dateTime(r.updated_at)}`:""}</p></div></div></form>`}
function renderEngineering(){
  const data=state.engineeringData;
  const actions=`<div class="engineering-period"><input id="engineeringPeriod" type="month" value="${state.engineeringPeriod}"><button class="secondary" data-go="work-orders">Ажлын самбар →</button><button class="secondary" id="engineeringRefresh">↻ Шинэчлэх</button>${data?.capabilities?.canCreate?'<button class="primary" data-open="workOrderDialog">+ Ажил төлөвлөх</button>':""}</div>`;
  if(!data){$("#pageContent").innerHTML=`${header("НЭГДСЭН ҮЙЛ АЖИЛЛАГАА","Ерөнхий инженерийн удирдлага","Гэрэлтүүлэг, камерын ажлын мэдээллийг нэгтгэж байна...",actions)}<div class="panel engineering-empty">Ачаалж байна...</div>`;if(!state.engineeringLoading)queueMicrotask(loadEngineering);return}
  if(data.error){$("#pageContent").innerHTML=`${header("НЭГДСЭН ҮЙЛ АЖИЛЛАГАА","Ерөнхий инженерийн удирдлага","Ажлын мэдээлэл ачаалсангүй.",actions)}<div class="panel engineering-empty">${esc(data.error)}</div>`;return}
  const all=data.items,lighting=engineeringDomainStats(all,"lighting"),camera=engineeringDomainStats(all,"camera"),open=all.filter(engineeringOpen),overdue=open.filter(engineeringOverdue),management=open.filter(x=>["awaiting_management_start","awaiting_management_completion"].includes(x.workflow_stage)),safety=open.filter(x=>["awaiting_safety_start","awaiting_safety_completion"].includes(x.workflow_stage)),unassigned=open.filter(x=>!x.assigned_to),done=all.filter(x=>x.status==="completed");
  const tabs=[["overview","Удирдлагын тойм"],["lighting","Гэрэлтүүлгийн хяналт"],["camera","Камерын хяналт"],["approvals",`Баталгаа (${management.length})`],["report","Сарын дүгнэлт"]];
  let body;if(state.engineeringTab==="lighting")body=`<section class="panel"><div class="panel-head"><h2>Гэрэлтүүлгийн ажлын удирдлага</h2><span>${lighting.total} ажил</span></div>${engineeringTable(lighting.rows)}</section>`;else if(state.engineeringTab==="camera")body=`<section class="panel"><div class="panel-head"><h2>Камерын ажлын удирдлага</h2><span>${camera.total} ажил</span></div>${engineeringTable(camera.rows)}</section>`;else if(state.engineeringTab==="approvals")body=`<section class="panel"><div class="panel-head"><h2>ХАБЭА ба удирдлагын шийдвэр хүлээж буй ажил</h2><span>${management.length+safety.length} ажил</span></div>${engineeringTable(all.filter(x=>["awaiting_safety_start","awaiting_management_start","awaiting_safety_completion","awaiting_management_completion"].includes(x.workflow_stage)))}</section>`;else if(state.engineeringTab==="report")body=engineeringReport(data);else body=`<div class="engineering-grid"><div><div class="engineering-grid">${engineeringDomainCard("Гэрэлтүүлэг",lighting,"lighting")}${engineeringDomainCard("Камер",camera,"camera")}</div><section class="panel"><div class="panel-head"><h2>Явцтай ажлууд</h2><button data-engineering-tab="approvals">Баталгааны дараалал →</button></div>${engineeringTable(open.slice(0,12))}</section></div><section class="panel"><div class="panel-head"><h2>Одоо анхаарах</h2><span>${overdue.length+unassigned.length+management.length}</span></div><div class="engineering-attention">${engineeringAttention(all)}</div></section></div>`;
  $("#pageContent").innerHTML=`${header("НЭГДСЭН ҮЙЛ АЖИЛЛАГАА","Ерөнхий инженерийн удирдлагын хяналт","Нэгдсэн Ажлын самбарын мэдээллээс удирдлагын шийдвэр, нөөц, нотолгоо, сарын дүгнэлтийг хянана.",actions)}<div class="engineering-kpis">${engineeringKpi("Нээлттэй ажил",open.length,"Одоо удирдах","#2870ed")}${engineeringKpi("Инженерийн шийдвэр",management.length,"Батлах эсвэл буцаах","#d69a00")}${engineeringKpi("ХАБЭА хүлээж буй",safety.length,"Аюулгүй ажиллагааны шат","#7a5af8")}${engineeringKpi("Хугацаа хэтэрсэн",overdue.length,"Яаралтай анхаарах","#d92d20")}${engineeringKpi("Хариуцагчгүй",unassigned.length,"Хуваарилах шаардлагатай","#f79009")}${engineeringKpi("Хаагдсан",done.length,"Сонгосон хугацаанд","#12a150")}</div><nav class="engineering-tabs">${tabs.map(([key,label])=>`<button class="${state.engineeringTab===key?"active":""}" data-engineering-tab="${key}">${label}</button>`).join("")}</nav>${body}`;
}

const engineeringWorkflowBefore=workflowAction;
workflowAction=async function(button){await engineeringWorkflowBefore(button);if(state.view==="engineering"){state.engineeringData=null;await loadEngineering(true)}};
document.addEventListener("click",event=>{const tab=event.target.closest("[data-engineering-tab]");if(tab){state.engineeringTab=tab.dataset.engineeringTab;render()}if(event.target.closest("#engineeringRefresh")){state.engineeringData=null;loadEngineering(true)}});
document.addEventListener("change",event=>{if(event.target.id==="engineeringPeriod"){state.engineeringPeriod=event.target.value;state.engineeringData=null;loadEngineering(true)}});
document.addEventListener("submit",async event=>{if(event.target.id!=="engineeringReviewForm")return;event.preventDefault();const form=event.target,{year,month}=engineeringPeriodParts();try{await api("/api/engineering/monthly-review",{method:"PUT",body:JSON.stringify({year,month,...Object.fromEntries(new FormData(form))})});state.engineeringData=null;await loadEngineering(true);toast("Ерөнхий инженерийн сарын дүгнэлт хадгалагдлаа")}catch(error){toast(error.message,true)}});
