"use strict";
labels.mobile="Талбарын апп";state.mobileData=null;if(new URLSearchParams(location.search).get("view")==="mobile")state.view="mobile";const MOBILE_CACHE="cop_mobile_work_v1",MOBILE_QUEUE="cop_mobile_queue_v1",renderBeforeMobile=render;render=function(){if(state.view!=="mobile")return renderBeforeMobile();renderMobile()};
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("/service-worker.js").catch(()=>{}));
function queueItems(){try{return JSON.parse(localStorage.getItem(MOBILE_QUEUE)||"[]")}catch{return []}}
function saveQueue(items){localStorage.setItem(MOBILE_QUEUE,JSON.stringify(items))}
async function loadMobile(){try{const result=await api("/api/work-orders");state.mobileData=result.items;localStorage.setItem(MOBILE_CACHE,JSON.stringify(result.items));await syncMobileQueue(false)}catch(error){try{state.mobileData=JSON.parse(localStorage.getItem(MOBILE_CACHE)||"[]");render();toast("Оффлайн хадгалсан мэдээллийг харуулж байна",true)}catch{toast(error.message,true)}}}
function myMobileJobs(){const all=state.mobileData||[];return all.filter(x=>x.assigned_to===state.user.id).filter(x=>!["completed","cancelled"].includes(x.status))}
function nextMobileAction(job){if(job.status==="assigned")return ["in_progress","Ажил эхлэх"];if(job.status==="in_progress")return ["pending_review","Шалгуулах"];return null}
function renderMobile(){if(!state.mobileData){$("#pageContent").innerHTML=header("FIELD OPERATIONS","Талбарын апп","Ажлын мэдээллийг ачаалж байна...");queueMicrotask(loadMobile);return}const jobs=myMobileJobs(),queued=queueItems();$("#pageContent").innerHTML=`<div class="mobile-shell">${header("FIELD OPERATIONS","Миний талбарын ажил","Утаснаас ажлаа эхлүүлэх, тэмдэглэл оруулах, шалгуулахад илгээх боломжтой.",`<button class="secondary" id="mobileSync">↻ Sync</button>`)}<div class="mobile-banner"><div><strong>OVERVA Field</strong><small>${esc(state.organization.name)} · ${esc(state.user.full_name)}</small></div><span class="mobile-online ${navigator.onLine?"online":""}">${navigator.onLine?"Онлайн":"Оффлайн"}</span></div>${queued.length?`<div class="mobile-queue">${queued.length} үйлдэл төхөөрөмж дээр хүлээгдэж байна. Интернэт ороход Sync хийнэ.</div>`:""}<div class="mobile-stats"><article class="mobile-stat"><strong>${jobs.length}</strong><small>Нээлттэй ажил</small></article><article class="mobile-stat"><strong>${jobs.filter(x=>x.priority==="emergency").length}</strong><small>Яаралтай</small></article><article class="mobile-stat"><strong>${queued.length}</strong><small>Оффлайн queue</small></article></div>${jobs.length?jobs.map(job=>{const action=nextMobileAction(job);return `<article class="mobile-job"><div class="mobile-job-head"><h3>${esc(job.title)}</h3><span class="badge ${job.priority}">${labels[job.priority]||job.priority}</span></div><div class="mobile-job-meta"><span>${esc(job.asset_code||"Хөрөнгөгүй")}</span><span>${esc(job.category)}</span><span>${job.due_at?dateTime(job.due_at):"Хугацаагүй"}</span><span>${labels[job.status]||job.status}</span></div><p>${esc(job.description||"Тайлбаргүй")}</p><div class="mobile-actions">${action?`<button class="primary" data-mobile-status="${job.id}" data-next-status="${action[0]}">${action[1]}</button>`:""}<button class="secondary" data-history-id="${job.id}">Түүх</button></div><form class="mobile-note" data-mobile-note="${job.id}"><input name="note" placeholder="Гүйцэтгэлийн тэмдэглэл..." required><button class="secondary">Нэмэх</button></form></article>`}).join(""):empty("Хуваарилсан ажил алга","Танд одоогоор нээлттэй ажил байхгүй байна.")}</div>`}
async function mobileAction(path,method,body,message){if(navigator.onLine){try{await api(path,{method,body:JSON.stringify(body)});state.mobileData=null;await loadMobile();toast(message);return}catch(error){if(error.message&&!/fetch|network/i.test(error.message))throw error}}const q=queueItems();q.push({id:crypto.randomUUID?.()||String(Date.now()),path,method,body,createdAt:new Date().toISOString()});saveQueue(q);render();toast("Оффлайн queue-д хадгаллаа")}
async function syncMobileQueue(show=true){if(!navigator.onLine)return show&&toast("Интернэт холболт алга",true);const q=queueItems(),remain=[];for(const item of q){try{await api(item.path,{method:item.method,body:JSON.stringify(item.body)})}catch{remain.push(item)}}saveQueue(remain);if(state.view==="mobile"&&q.length){const result=await api("/api/work-orders");state.mobileData=result.items;localStorage.setItem(MOBILE_CACHE,JSON.stringify(result.items));render()}if(show)toast(remain.length?`${remain.length} үйлдэл sync хийгдээгүй`:`${q.length} үйлдэл sync хийгдлээ`,!!remain.length)}
document.addEventListener("click",async event=>{const status=event.target.closest("[data-mobile-status]");try{if(status)await mobileAction(`/api/work-orders/${status.dataset.mobileStatus}/status`,"PATCH",{status:status.dataset.nextStatus},"Ажлын төлөв шинэчлэгдлээ");if(event.target.closest("#mobileSync"))await syncMobileQueue()}catch(error){toast(error.message,true)}});
document.addEventListener("submit",async event=>{const f=event.target;if(!f.matches("[data-mobile-note]"))return;event.preventDefault();try{const note=new FormData(f).get("note");await mobileAction(`/api/work-orders/${f.dataset.mobileNote}/notes`,"POST",{note},"Тэмдэглэл нэмэгдлээ")}catch(error){toast(error.message,true)}});
window.addEventListener("online",()=>syncMobileQueue(false));
