"use strict";

labels.safety="ХАБЭА";
state.safetyData=null;
const safetyRenderBefore=render;
render=function(){if(state.view!=="safety")return safetyRenderBefore();renderSafety()};
const safetyAdjustBefore=adjustModuleNavigation;
adjustModuleNavigation=function(){safetyAdjustBefore();if(state.user)$("#safetyNav")?.classList.remove("hidden")};

const safetyRiskLabels={low:"Бага",medium:"Дунд",high:"Өндөр",critical:"Ноцтой"};
const safetyStatusLabels={open:"Нээлттэй",in_progress:"Арга хэмжээ авч буй",controlled:"Хяналтад орсон",closed:"Хаасан",reported:"Мэдээлсэн",investigating:"Шалгаж буй",corrective_action:"Залруулах арга хэмжээ",induction:"Анхан",toolbox:"Ажлын өмнөх",refresher:"Давтан",emergency:"Онцгой үеийн",other:"Бусад",unsafe_condition:"Аюултай нөхцөл",near_miss:"Осолд дөхсөн",incident:"Осол, зөрчил",injury:"Гэмтэл",occupational_illness:"Мэргэжлээс шалтгаалах өвчин",property_damage:"Эд хөрөнгийн хохирол",environmental:"Байгаль орчны"};
const safetyDt=value=>value?new Date(value).toLocaleString("mn-MN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}):"—";

async function loadSafety(){try{state.safetyData=await api("/api/safety/overview");render()}catch(error){toast(error.message,true)}}
function safetyOptions(items,selected=""){return `<option value="">Хариуцагч сонгохгүй</option>`+items.map(x=>`<option value="${x.id}" ${x.id===selected?"selected":""}>${esc(x.full_name)}</option>`).join("")}
function riskStatusControl(item,canManage){if(!canManage)return `<span class="safety-pill status-${item.status}">${safetyStatusLabels[item.status]||item.status}</span>`;return `<select class="safety-status" data-safety-risk="${item.id}">${["open","in_progress","controlled","closed"].map(x=>`<option value="${x}" ${x===item.status?"selected":""}>${safetyStatusLabels[x]}</option>`).join("")}</select>`}
function incidentStatusControl(item,canManage){if(!canManage)return `<span class="safety-pill status-${item.status}">${safetyStatusLabels[item.status]||item.status}</span>`;return `<select class="safety-status" data-safety-incident="${item.id}">${["reported","investigating","corrective_action","closed"].map(x=>`<option value="${x}" ${x===item.status?"selected":""}>${safetyStatusLabels[x]}</option>`).join("")}</select>`}

function renderSafety(){const d=state.safetyData;if(!d){$("#pageContent").innerHTML=header("OVERVA SAFETY","Хөдөлмөрийн аюулгүй байдал","Эрсдэл, осол зөрчил болон зааварчилгааны мэдээллийг ачаалж байна...");queueMicrotask(loadSafety);return}const s=d.summary,can=d.canManage;
  const riskRows=d.risks.map(x=>`<tr><td><strong>${esc(x.reference_no)}</strong><small>${date(x.created_at)}</small></td><td><strong>${esc(x.title)}</strong><small>${esc(x.category)} · ${esc(x.location||"Байршилгүй")}</small></td><td><span class="safety-pill risk-${x.risk_band}">${x.risk_score} · ${safetyRiskLabels[x.risk_band]}</span><small>Магадлал ${x.likelihood} × Үр дагавар ${x.severity}</small></td><td>${esc(x.responsible_name||"—")}<small>${x.due_date?`Хугацаа: ${date(x.due_date)}`:"Хугацаагүй"}</small></td><td>${riskStatusControl(x,can)}</td></tr>`).join("");
  const incidentRows=d.incidents.map(x=>`<tr><td><strong>${esc(x.reference_no)}</strong><small>${safetyDt(x.occurred_at)}</small></td><td><strong>${safetyStatusLabels[x.incident_type]||x.incident_type}</strong><small>${esc(x.location||"Байршилгүй")}</small></td><td>${esc(x.description)}<small>${esc(x.immediate_action||"Шуурхай арга хэмжээ бичигдээгүй")}</small></td><td><span class="safety-pill risk-${x.severity}">${safetyRiskLabels[x.severity]||x.severity}</span><small>${x.injured_count} гэмтсэн · ${x.lost_time?"Алдагдсан цагтай":"Алдагдсан цаггүй"}</small></td><td>${incidentStatusControl(x,can)}</td></tr>`).join("");
  $("#pageContent").innerHTML=`${header("OVERVA SAFETY","ХАБЭА хяналтын самбар","Аюулыг эрт мэдээлж, эрсдэлийг үнэлэн, залруулах арга хэмжээг хаах хүртэл хянана.")}<div class="safety-cards"><article><span>Нээлттэй эрсдэл</span><strong>${s.open_risks}</strong></article><article class="danger"><span>Ноцтой эрсдэл</span><strong>${s.critical_risks}</strong></article><article class="warn"><span>Хугацаа хэтэрсэн арга хэмжээ</span><strong>${s.overdue_actions}</strong></article><article><span>Нээлттэй осол, зөрчил</span><strong>${s.open_incidents}</strong></article><article><span>Энэ сарын мэдээлэл</span><strong>${s.incidents_this_month}</strong></article><article class="good"><span>Энэ сард зааварчилсан</span><strong>${s.briefed_this_month}</strong></article></div>
  <div class="safety-form-grid"><form class="safety-form" id="safetyRiskForm"><h2>⚠ Эрсдэл мэдээлэх</h2><label>Гарчиг<input name="title" required maxlength="250" placeholder="Илэрсэн аюул, эрсдэлийн товч нэр"></label><div class="safety-fields"><label>Ангилал<input name="category" required placeholder="Уналт, цахилгаан, гал, эрүүл ахуй..."></label><label>Байршил<input name="location" placeholder="Хаана илэрсэн"></label><label>Магадлал (1–5)<input name="likelihood" type="number" min="1" max="5" value="3" required></label><label>Үр дагавар (1–5)<input name="severity" type="number" min="1" max="5" value="3" required></label><label>Хариуцагч<select name="responsibleUserId">${safetyOptions(state.assignableUsers)}</select></label><label>Арга хэмжээний хугацаа<input name="dueDate" type="date"></label></div><label>Нөхцөл, тайлбар<textarea name="description" rows="3" required></textarea></label><label>Одоогийн хамгаалалт<textarea name="existingControls" rows="2"></textarea></label><button class="primary">Эрсдэл бүртгэх</button></form>
  <form class="safety-form" id="safetyIncidentForm"><h2>✚ Осол, зөрчил мэдээлэх</h2><div class="safety-fields"><label>Төрөл<select name="incidentType"><option value="unsafe_condition">Аюултай нөхцөл</option><option value="near_miss">Осолд дөхсөн</option><option value="incident">Осол, зөрчил</option><option value="injury">Гэмтэл</option><option value="occupational_illness">Мэргэжлээс шалтгаалах өвчин</option><option value="property_damage">Эд хөрөнгийн хохирол</option><option value="environmental">Байгаль орчны</option></select></label><label>Ноцтой байдал<select name="severity"><option value="low">Бага</option><option value="medium">Дунд</option><option value="high">Өндөр</option><option value="critical">Ноцтой</option></select></label><label>Болсон огноо, цаг<input name="occurredAt" type="datetime-local" required></label><label>Байршил<input name="location"></label><label>Гэмтсэн хүний тоо<input name="injuredCount" type="number" min="0" value="0"></label><label class="safety-check"><input name="lostTime" type="checkbox"> Ажил тасалдсан</label></div><label>Юу болсон<textarea name="description" rows="3" required></textarea></label><label>Шуурхай авсан арга хэмжээ<textarea name="immediateAction" rows="2"></textarea></label><button class="primary">Мэдээлэл бүртгэх</button></form></div>
  ${can?`<form class="safety-form safety-briefing" id="safetyBriefingForm"><h2>▣ Зааварчилгаа бүртгэх</h2><div class="safety-fields"><label>Төрөл<select name="briefingType"><option value="induction">Анхан</option><option value="toolbox">Ажлын өмнөх</option><option value="refresher">Давтан</option><option value="emergency">Онцгой үеийн</option><option value="other">Бусад</option></select></label><label>Сэдэв<input name="title" required></label><label>Огноо, цаг<input name="conductedAt" type="datetime-local" required></label><label>Зааварлагч<select name="facilitatorUserId">${safetyOptions(state.assignableUsers,state.user.id)}</select></label><label>Байршил<input name="location"></label><label>Оролцсон хүний тоо<input name="attendeeCount" type="number" min="0" value="0"></label></div><label>Агуулга<textarea name="content" rows="2"></textarea></label><button class="secondary">Зааварчилгаа хадгалах</button></form>`:""}
  <section class="safety-panel"><div class="panel-head"><h2>Эрсдэлийн бүртгэл</h2><span>${d.risks.length} бүртгэл</span></div><div class="safety-table-wrap"><table class="safety-table"><thead><tr><th>Дугаар</th><th>Эрсдэл</th><th>Үнэлгээ</th><th>Хариуцагч</th><th>Төлөв</th></tr></thead><tbody>${riskRows||`<tr><td colspan="5">Эрсдэл бүртгэгдээгүй байна.</td></tr>`}</tbody></table></div></section>
  <section class="safety-panel"><div class="panel-head"><h2>Осол, зөрчил, аюултай нөхцөл</h2><span>${d.incidents.length} бүртгэл</span></div><div class="safety-table-wrap"><table class="safety-table"><thead><tr><th>Дугаар</th><th>Төрөл</th><th>Тайлбар</th><th>Ноцтой байдал</th><th>Төлөв</th></tr></thead><tbody>${incidentRows||`<tr><td colspan="5">Осол, зөрчил бүртгэгдээгүй байна.</td></tr>`}</tbody></table></div></section>
  <section class="safety-panel"><div class="panel-head"><h2>Сүүлийн зааварчилгаа</h2></div><div class="safety-brief-list">${d.briefings.map(x=>`<article><div><strong>${esc(x.title)}</strong><small>${safetyStatusLabels[x.briefing_type]||x.briefing_type} · ${safetyDt(x.conducted_at)} · ${esc(x.location||"Байршилгүй")}</small></div><b>${x.attendee_count} хүн</b></article>`).join("")||"Зааварчилгаа бүртгэгдээгүй байна."}</div></section>`}

async function safetyReload(message){state.safetyData=null;await loadSafety();if(message)toast(message)}
document.addEventListener("submit",async event=>{const f=event.target;if(!["safetyRiskForm","safetyIncidentForm","safetyBriefingForm"].includes(f.id))return;event.preventDefault();try{const data=new FormData(f),v=Object.fromEntries(data);if(v.occurredAt)v.occurredAt=new Date(v.occurredAt).toISOString();if(v.conductedAt)v.conductedAt=new Date(v.conductedAt).toISOString();if(f.id==="safetyIncidentForm")v.lostTime=data.has("lostTime");const path=f.id==="safetyRiskForm"?"/api/safety/risks":f.id==="safetyIncidentForm"?"/api/safety/incidents":"/api/safety/briefings";await api(path,{method:"POST",body:JSON.stringify(v)});f.reset();await safetyReload("ХАБЭА мэдээлэл хадгалагдлаа")}catch(error){toast(error.message,true)}});
document.addEventListener("change",async event=>{const risk=event.target.closest("[data-safety-risk]"),incident=event.target.closest("[data-safety-incident]");if(!risk&&!incident)return;try{if(risk)await api(`/api/safety/risks/${risk.dataset.safetyRisk}`,{method:"PATCH",body:JSON.stringify({status:risk.value})});if(incident)await api(`/api/safety/incidents/${incident.dataset.safetyIncident}`,{method:"PATCH",body:JSON.stringify({status:incident.value})});await safetyReload("Төлөв шинэчлэгдлээ")}catch(error){toast(error.message,true);await safetyReload()}});
