"use strict";
const crypto=require("node:crypto"),{getPool}=require("../db"),{loadConfig}=require("../config");
function secretFor(id){return `whsec_${crypto.createHmac("sha256",loadConfig().JWT_SECRET).update(id).digest("hex")}`}
function safeUrl(raw){const u=new URL(raw);if(!["http:","https:"].includes(u.protocol))throw new Error("Webhook URL must be HTTP(S)");if(process.env.NODE_ENV==="production"){if(u.protocol!=="https:")throw new Error("Production webhook must use HTTPS");const h=u.hostname.toLowerCase();if(h==="localhost"||h==="::1"||/^127\./.test(h)||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||/^172\.(1[6-9]|2\d|3[01])\./.test(h))throw new Error("Private webhook address is not allowed")};return u.toString()}
function retryDelaySeconds(delivery){return Math.min(86400,Number(delivery.retry_backoff_seconds||60)*2**Math.max(0,Number(delivery.attempts||0)))}
function nextFailureStatus(delivery){return Number(delivery.attempts||0)+1>=Number(delivery.max_attempts||5)?"dead_letter":"failed"}
async function markFailure(delivery,{responseStatus=null,responseBody="",message}){const status=nextFailureStatus(delivery),delay=retryDelaySeconds(delivery);await getPool().query(`UPDATE webhook_deliveries SET attempts=attempts+1,status=$2,response_status=$3,response_body=$4,last_error=$5,next_attempt_at=CASE WHEN $2='dead_letter' THEN next_attempt_at ELSE now()+($6::text||' seconds')::interval END WHERE id=$1`,[delivery.id,status,responseStatus,responseBody,String(message).slice(0,1000),delay]);return status}
async function deliverWebhook(id){const result=await getPool().query(`SELECT d.*,s.url FROM webhook_deliveries d JOIN webhook_subscriptions s ON s.organization_id=d.organization_id AND s.id=d.subscription_id WHERE d.id=$1 AND s.active=true`,[id]);if(!result.rowCount)return;const d=result.rows[0];if(d.status==="delivered"||d.status==="dead_letter")return;const body=JSON.stringify({id:d.id,type:d.event_type,createdAt:d.created_at,data:d.payload}),timestamp=Math.floor(Date.now()/1000),signature=crypto.createHmac("sha256",secretFor(d.subscription_id)).update(`${timestamp}.${body}`).digest("hex");try{const response=await fetch(safeUrl(d.url),{method:"POST",headers:{"content-type":"application/json","user-agent":"OVERVA-Webhook/1.0","x-overva-event":d.event_type,"x-overva-delivery":d.id,"x-overva-timestamp":String(timestamp),"x-overva-signature":`v1=${signature}`,"x-cop-event":d.event_type,"x-cop-timestamp":String(timestamp),"x-cop-signature":`v1=${signature}`},body,redirect:"error",signal:AbortSignal.timeout(8000)}),text=(await response.text()).slice(0,2000);if(response.ok){await getPool().query(`UPDATE webhook_deliveries SET attempts=attempts+1,status='delivered',response_status=$2,response_body=$3,last_error='',delivered_at=now() WHERE id=$1`,[id,response.status,text]);return "delivered"}return markFailure(d,{responseStatus:response.status,responseBody:text,message:`HTTP ${response.status}`})}catch(error){return markFailure(d,{message:error.message})}}
async function queueWebhookEvent(organizationId,eventType,payload){const eventKey=payload?.eventId?String(payload.eventId):crypto.createHash("sha256").update(JSON.stringify(payload)).digest("hex");const rows=await getPool().query(`INSERT INTO webhook_deliveries(organization_id,subscription_id,event_type,payload,idempotency_key) SELECT organization_id,id,$2,$3,$4 FROM webhook_subscriptions WHERE organization_id=$1 AND active=true AND ($2=ANY(event_types) OR '*'=ANY(event_types)) ON CONFLICT(organization_id,subscription_id,idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING RETURNING id`,[organizationId,eventType,payload,`${eventType}:${eventKey}`]);return rows.rowCount}
module.exports={secretFor,safeUrl,retryDelaySeconds,nextFailureStatus,deliverWebhook,queueWebhookEvent};
