"use strict";
const express=require("express");
const {getPool}=require("../db");
const {authenticate,requireRoles,requireModule}=require("../middleware/auth");
const {asyncHandler}=require("../utils/async-handler");
const router=express.Router();
router.use(authenticate,requireModule("executive"),requireRoles("director","chief_engineer","accountant"));
router.get("/overview",asyncHandler(async(req,res)=>{const org=req.user.organization_id,enabled=new Set(req.user.enabled_modules||[]),[people,assets,work,inventory,maintenance,procurement,finance,fleet,iot,workTrend]=await Promise.all([
 getPool().query(`SELECT count(*) FILTER(WHERE active)::int AS active,count(*) FILTER(WHERE NOT active)::int AS inactive FROM users WHERE organization_id=$1`,[org]),
 getPool().query(`SELECT count(*)::int AS total,count(*) FILTER(WHERE status='active')::int AS active,count(*) FILTER(WHERE status='repair')::int AS repair FROM assets WHERE organization_id=$1 AND COALESCE(metadata->>'excludedFromAssetMaster','false')<>'true'`,[org]),
 getPool().query(`SELECT count(*) FILTER(WHERE status IN ('new','assigned','in_progress','pending_review'))::int AS open,count(*) FILTER(WHERE priority='emergency' AND status NOT IN ('completed','cancelled'))::int AS emergency,count(*) FILTER(WHERE status='completed' AND updated_at>=date_trunc('month',now()))::int AS completed_month,count(*) FILTER(WHERE due_at<now() AND status NOT IN ('completed','cancelled'))::int AS overdue FROM work_orders WHERE organization_id=$1`,[org]),
 getPool().query(`SELECT count(*) FILTER(WHERE total_quantity<=minimum_stock)::int AS low_stock,count(*)::int AS item_count FROM (SELECT i.id,i.minimum_stock,COALESCE(sum(b.quantity),0) AS total_quantity FROM inventory_items i LEFT JOIN inventory_balances b ON b.organization_id=i.organization_id AND b.item_id=i.id WHERE i.organization_id=$1 GROUP BY i.id) q`,[org]),
 getPool().query(`SELECT count(*) FILTER(WHERE active)::int AS active,count(*) FILTER(WHERE active AND next_due_date<CURRENT_DATE)::int AS overdue FROM maintenance_plans WHERE organization_id=$1`,[org]),
 getPool().query(`SELECT count(*) FILTER(WHERE status='submitted')::int AS awaiting,COALESCE(sum(total_amount) FILTER(WHERE status='submitted'),0)::numeric AS awaiting_amount FROM purchase_requests WHERE organization_id=$1`,[org]),
 getPool().query(`SELECT COALESCE(sum(amount) FILTER(WHERE transaction_type='income'),0)::numeric AS income,COALESCE(sum(amount) FILTER(WHERE transaction_type='expense'),0)::numeric AS expense,COALESCE(sum(amount) FILTER(WHERE transaction_type='receivable'),0)::numeric AS receivable,COALESCE(sum(amount) FILTER(WHERE transaction_type='payable'),0)::numeric AS payable FROM finance_transactions WHERE organization_id=$1 AND transaction_date>=date_trunc('month',CURRENT_DATE)`,[org]),
 getPool().query(`SELECT count(*)::int AS total,count(*) FILTER(WHERE p.recorded_at>now()-interval '5 minutes')::int AS online,count(*) FILTER(WHERE p.recorded_at>now()-interval '5 minutes' AND p.speed_kph>3)::int AS moving FROM fleet_vehicles v LEFT JOIN LATERAL(SELECT recorded_at,speed_kph FROM gps_positions gp WHERE gp.organization_id=v.organization_id AND gp.vehicle_id=v.id ORDER BY recorded_at DESC LIMIT 1)p ON true WHERE v.organization_id=$1 AND v.status='active'`,[org]),
 getPool().query(`SELECT count(*)::int AS total,count(*) FILTER(WHERE last_seen_at>now()-interval '5 minutes')::int AS online,count(*) FILTER(WHERE t.health IN ('fault','critical'))::int AS fault FROM iot_devices d LEFT JOIN LATERAL(SELECT health FROM iot_telemetry it WHERE it.organization_id=d.organization_id AND it.device_id=d.id ORDER BY recorded_at DESC LIMIT 1)t ON true WHERE d.organization_id=$1 AND d.active`,[org]),
 getPool().query(`SELECT to_char(day,'MM-DD') AS day,COALESCE(created,0)::int AS created,COALESCE(completed,0)::int AS completed FROM generate_series(CURRENT_DATE-interval '13 days',CURRENT_DATE,interval '1 day') day LEFT JOIN(SELECT date(created_at) d,count(*) created FROM work_orders WHERE organization_id=$1 AND created_at>=CURRENT_DATE-interval '13 days' GROUP BY 1)c ON c.d=day LEFT JOIN(SELECT date(created_at) d,count(*) completed FROM work_order_events WHERE organization_id=$1 AND event_type='status_changed' AND to_status='completed' AND created_at>=CURRENT_DATE-interval '13 days' GROUP BY 1)x ON x.d=day ORDER BY day`,[org])
 ]);const data={people:people.rows[0],assets:assets.rows[0],work:work.rows[0],inventory:inventory.rows[0],maintenance:maintenance.rows[0],procurement:procurement.rows[0],finance:finance.rows[0],fleet:fleet.rows[0],iot:iot.rows[0],workTrend:workTrend.rows};const alerts=[];if(enabled.has("work-orders")&&data.work.emergency>0)alerts.push({level:"critical",module:"Ажил",message:`${data.work.emergency} яаралтай ажил нээлттэй байна`});if(enabled.has("work-orders")&&data.work.overdue>0)alerts.push({level:"warning",module:"Ажил",message:`${data.work.overdue} ажил хугацаа хэтэрсэн`});if(enabled.has("inventory")&&data.inventory.low_stock>0)alerts.push({level:"warning",module:"Агуулах",message:`${data.inventory.low_stock} бараа доод үлдэгдэлд хүрсэн`});if(enabled.has("maintenance")&&data.maintenance.overdue>0)alerts.push({level:"warning",module:"Засвар",message:`${data.maintenance.overdue} төлөвлөгөөний хугацаа хэтэрсэн`});if(enabled.has("iot")&&data.iot.fault>0)alerts.push({level:"critical",module:"IoT",message:`${data.iot.fault} төхөөрөмж алдаатай`});if(enabled.has("procurement")&&data.procurement.awaiting>0)alerts.push({level:"info",module:"Худалдан авалт",message:`${data.procurement.awaiting} хүсэлт шийдвэр хүлээж байна`});const penalties=alerts.reduce((sum,item)=>sum+(item.level==="critical"?8:item.level==="warning"?3:1),0);data.healthScore=Math.max(0,Math.min(100,100-penalties));data.alerts=alerts;data.generatedAt=new Date().toISOString();res.json(data)}));
module.exports=router;
