"use strict";

const express=require("express");
const crypto=require("node:crypto");
const {rateLimit}=require("express-rate-limit");
const {z}=require("zod");
const {getPool}=require("../db");
const {authenticate,requireRoles,requireModule}=require("../middleware/auth");
const {writeAudit}=require("../services/audit");
const {asyncHandler}=require("../utils/async-handler");

const router=express.Router();
const uuid=z.string().uuid();
const managers=requireRoles("director","chief_engineer");
const ingestSchema=z.object({latitude:z.coerce.number().min(-90).max(90),longitude:z.coerce.number().min(-180).max(180),speedKph:z.coerce.number().min(0).max(400).default(0),heading:z.coerce.number().min(0).max(359.99).nullable().optional(),altitudeM:z.coerce.number().min(-500).max(10000).nullable().optional(),ignition:z.boolean().nullable().optional(),fuelLevelPct:z.coerce.number().min(0).max(100).nullable().optional(),odometerKm:z.coerce.number().min(0).nullable().optional(),accuracyM:z.coerce.number().min(0).max(10000).nullable().optional(),recordedAt:z.iso.datetime(),metadata:z.record(z.string(),z.unknown()).default({})});
const hash=value=>crypto.createHash("sha256").update(value).digest("hex");
function distanceMeters(aLat,aLng,bLat,bLng){const r=6371000,toRad=x=>x*Math.PI/180,dLat=toRad(bLat-aLat),dLng=toRad(bLng-aLng),a=Math.sin(dLat/2)**2+Math.cos(toRad(aLat))*Math.cos(toRad(bLat))*Math.sin(dLng/2)**2;return 2*r*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}

router.post("/ingest",rateLimit({windowMs:60_000,limit:3000,standardHeaders:true,legacyHeaders:false}),asyncHandler(async(req,res)=>{
  const key=String(req.headers["x-device-key"]||"");if(!/^gps_[a-f0-9]{64}$/.test(key))return res.status(401).json({error:"Invalid device key"});
  const parsed=ingestSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Invalid GPS position",issues:parsed.error.issues});const v=parsed.data,client=await getPool().connect();
  try{await client.query("BEGIN");const deviceResult=await client.query(`SELECT d.id,d.organization_id,d.vehicle_id FROM gps_devices d JOIN fleet_vehicles v ON v.organization_id=d.organization_id AND v.id=d.vehicle_id JOIN organizations o ON o.id=d.organization_id JOIN subscriptions s ON s.organization_id=o.id JOIN organization_modules om ON om.organization_id=o.id AND om.module_code='fleet' AND om.enabled=true WHERE d.api_key_hash=$1 AND d.active=true AND v.status<>'inactive' AND o.status='active' AND s.status IN('trial','active','past_due') FOR UPDATE`,[hash(key)]);if(!deviceResult.rowCount){await client.query("ROLLBACK");return res.status(401).json({error:"Device unavailable"})}const d=deviceResult.rows[0];
    const position=await client.query(`INSERT INTO gps_positions(organization_id,vehicle_id,device_id,latitude,longitude,speed_kph,heading,altitude_m,ignition,fuel_level_pct,odometer_km,accuracy_m,recorded_at,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb) RETURNING id,received_at`,[d.organization_id,d.vehicle_id,d.id,v.latitude,v.longitude,v.speedKph,v.heading??null,v.altitudeM??null,v.ignition??null,v.fuelLevelPct??null,v.odometerKm??null,v.accuracyM??null,v.recordedAt,JSON.stringify(v.metadata)]);
    await client.query(`UPDATE gps_devices SET last_seen_at=now(),updated_at=now() WHERE id=$1`,[d.id]);if(v.odometerKm!=null)await client.query(`UPDATE fleet_vehicles SET odometer_km=GREATEST(odometer_km,$3),updated_at=now() WHERE organization_id=$1 AND id=$2`,[d.organization_id,d.vehicle_id,v.odometerKm]);
    const fences=await client.query(`SELECT id,center_lat,center_lng,radius_m FROM geofences WHERE organization_id=$1 AND active=true`,[d.organization_id]);for(const fence of fences.rows){const inside=distanceMeters(Number(fence.center_lat),Number(fence.center_lng),v.latitude,v.longitude)<=fence.radius_m;const previous=await client.query(`SELECT is_inside FROM vehicle_geofence_states WHERE organization_id=$1 AND vehicle_id=$2 AND geofence_id=$3 FOR UPDATE`,[d.organization_id,d.vehicle_id,fence.id]);if(previous.rowCount&&previous.rows[0].is_inside!==inside)await client.query(`INSERT INTO geofence_events(organization_id,vehicle_id,geofence_id,event_type,latitude,longitude,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7)`,[d.organization_id,d.vehicle_id,fence.id,inside?"entered":"exited",v.latitude,v.longitude,v.recordedAt]);await client.query(`INSERT INTO vehicle_geofence_states(organization_id,vehicle_id,geofence_id,is_inside,changed_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT(organization_id,vehicle_id,geofence_id) DO UPDATE SET is_inside=EXCLUDED.is_inside,changed_at=CASE WHEN vehicle_geofence_states.is_inside<>EXCLUDED.is_inside THEN EXCLUDED.changed_at ELSE vehicle_geofence_states.changed_at END`,[d.organization_id,d.vehicle_id,fence.id,inside,v.recordedAt]);}
    await client.query("COMMIT");res.status(202).json({ok:true,positionId:position.rows[0].id,receivedAt:position.rows[0].received_at});
  }catch(error){await client.query("ROLLBACK").catch(()=>{});throw error}finally{client.release()}
}));

router.use(authenticate,requireModule("fleet"));
router.get("/overview",asyncHandler(async(req,res)=>{const org=req.user.organization_id;const [vehicles,geofences,events]=await Promise.all([
  getPool().query(`SELECT v.*,a.code AS asset_code,a.name AS asset_name,u.full_name AS driver_name,d.id AS device_id,d.device_uid,d.provider,d.active AS device_active,d.last_seen_at,p.latitude,p.longitude,p.speed_kph,p.heading,p.ignition,p.fuel_level_pct,p.recorded_at,(p.recorded_at>now()-interval '5 minutes') AS online FROM fleet_vehicles v JOIN assets a ON a.organization_id=v.organization_id AND a.id=v.asset_id LEFT JOIN users u ON u.organization_id=v.organization_id AND u.id=v.driver_user_id LEFT JOIN gps_devices d ON d.organization_id=v.organization_id AND d.vehicle_id=v.id LEFT JOIN LATERAL(SELECT * FROM gps_positions p WHERE p.organization_id=v.organization_id AND p.vehicle_id=v.id ORDER BY p.recorded_at DESC LIMIT 1)p ON true WHERE v.organization_id=$1 ORDER BY v.status,v.plate_number`,[org]),
  getPool().query(`SELECT * FROM geofences WHERE organization_id=$1 AND active=true ORDER BY name`,[org]),
  getPool().query(`SELECT e.*,v.plate_number,g.name AS geofence_name FROM geofence_events e JOIN fleet_vehicles v ON v.organization_id=e.organization_id AND v.id=e.vehicle_id JOIN geofences g ON g.organization_id=e.organization_id AND g.id=e.geofence_id WHERE e.organization_id=$1 ORDER BY e.occurred_at DESC LIMIT 100`,[org])]);res.json({vehicles:vehicles.rows,geofences:geofences.rows,events:events.rows});}));

router.get("/vehicles/:id/history",asyncHandler(async(req,res)=>{const id=uuid.safeParse(req.params.id),query=z.object({from:z.iso.datetime().optional(),to:z.iso.datetime().optional(),limit:z.coerce.number().int().min(1).max(5000).default(2000)}).safeParse(req.query);if(!id.success||!query.success)return res.status(400).json({error:"Invalid history request"});const to=query.data.to||new Date().toISOString(),from=query.data.from||new Date(Date.now()-24*3600_000).toISOString();const vehicle=await getPool().query(`SELECT id,plate_number FROM fleet_vehicles WHERE organization_id=$1 AND id=$2`,[req.user.organization_id,id.data]);if(!vehicle.rowCount)return res.status(404).json({error:"Vehicle not found"});const positions=await getPool().query(`SELECT id,latitude,longitude,speed_kph,heading,ignition,fuel_level_pct,odometer_km,recorded_at FROM gps_positions WHERE organization_id=$1 AND vehicle_id=$2 AND recorded_at BETWEEN $3 AND $4 ORDER BY recorded_at ASC LIMIT $5`,[req.user.organization_id,id.data,from,to,query.data.limit]);res.json({vehicle:vehicle.rows[0],from,to,items:positions.rows});}));

router.post("/vehicles",managers,asyncHandler(async(req,res)=>{const parsed=z.object({assetId:uuid,plateNumber:z.string().trim().min(2).max(30).transform(v=>v.toUpperCase()),make:z.string().trim().max(100).default(""),model:z.string().trim().max(100).default(""),driverUserId:uuid.nullable().optional(),odometerKm:z.coerce.number().min(0).default(0),fuelCapacityL:z.coerce.number().positive().nullable().optional()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Тээврийн хэрэгслийн мэдээлэл буруу байна"});const v=parsed.data;const result=await getPool().query(`INSERT INTO fleet_vehicles(organization_id,asset_id,plate_number,make,model,driver_user_id,odometer_km,fuel_capacity_l,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[req.user.organization_id,v.assetId,v.plateNumber,v.make,v.model,v.driverUserId||null,v.odometerKm,v.fuelCapacityL||null,req.user.id]);await writeAudit(req,"fleet.vehicle_create","fleet_vehicle",result.rows[0].id,{plateNumber:v.plateNumber,assetId:v.assetId});res.status(201).json({item:result.rows[0]});}));

router.post("/devices",managers,asyncHandler(async(req,res)=>{const parsed=z.object({vehicleId:uuid,deviceUid:z.string().trim().min(3).max(120),provider:z.string().trim().min(2).max(80).default("generic")}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"GPS төхөөрөмжийн мэдээлэл буруу байна"});const v=parsed.data,apiKey=`gps_${crypto.randomBytes(32).toString("hex")}`;const result=await getPool().query(`INSERT INTO gps_devices(organization_id,vehicle_id,device_uid,provider,api_key_hash,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,vehicle_id,device_uid,provider,active,created_at`,[req.user.organization_id,v.vehicleId,v.deviceUid,v.provider,hash(apiKey),req.user.id]);await writeAudit(req,"gps.device_create","gps_device",result.rows[0].id,{vehicleId:v.vehicleId,deviceUid:v.deviceUid,provider:v.provider});res.status(201).json({item:result.rows[0],apiKey,warning:"Энэ түлхүүр дахин харагдахгүй. GPS provider дээр аюулгүй хадгална уу."});}));

router.post("/devices/:id/rotate-key",managers,asyncHandler(async(req,res)=>{const id=uuid.safeParse(req.params.id);if(!id.success)return res.status(400).json({error:"Invalid device"});const apiKey=`gps_${crypto.randomBytes(32).toString("hex")}`;const result=await getPool().query(`UPDATE gps_devices SET api_key_hash=$3,updated_at=now() WHERE organization_id=$1 AND id=$2 RETURNING id`,[req.user.organization_id,id.data,hash(apiKey)]);if(!result.rowCount)return res.status(404).json({error:"Device not found"});await writeAudit(req,"gps.key_rotate","gps_device",id.data,{});res.json({apiKey,warning:"Хуучин түлхүүр хүчингүй боллоо."});}));

router.post("/geofences",managers,asyncHandler(async(req,res)=>{const parsed=z.object({name:z.string().trim().min(2).max(150),latitude:z.coerce.number().min(-90).max(90),longitude:z.coerce.number().min(-180).max(180),radiusM:z.coerce.number().int().min(10).max(100000),color:z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#f59e0b")}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Geofence мэдээлэл буруу байна"});const v=parsed.data;const result=await getPool().query(`INSERT INTO geofences(organization_id,name,center_lat,center_lng,radius_m,color,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[req.user.organization_id,v.name,v.latitude,v.longitude,v.radiusM,v.color,req.user.id]);await writeAudit(req,"gps.geofence_create","geofence",result.rows[0].id,v);res.status(201).json({item:result.rows[0]});}));

module.exports=router;
