"use strict";
const express=require("express");
const {z}=require("zod");
const {getPool}=require("../db");
const {authenticate,requireRoles,requireModule}=require("../middleware/auth");
const {writeAudit}=require("../services/audit");
const {asyncHandler}=require("../utils/async-handler");
const router=express.Router(),managers=requireRoles("director","chief_engineer"),uuid=z.string().uuid();
const canonical={gps:["latitude","longitude","speedKph","heading","altitudeM","ignition","fuelLevelPct","odometerKm","accuracyM","recordedAt"],iot:["state","health","voltage","currentAmp","powerWatt","energyKwh","temperatureC","signalStrength","recordedAt"]};
function atPath(value,path){return String(path||"").split(".").filter(Boolean).reduce((x,k)=>x==null?undefined:x[k],value)}
function mapPayload(payload,mapping,type){const out={};for(const field of canonical[type]){const path=mapping[field]||field,value=atPath(payload,path);if(value!==undefined)out[field]=value}return out}
function validate(type,value){const schema=type==="gps"?z.object({latitude:z.coerce.number().min(-90).max(90),longitude:z.coerce.number().min(-180).max(180),speedKph:z.coerce.number().min(0).max(400).default(0),recordedAt:z.iso.datetime()}):z.object({state:z.string().min(1).default("unknown"),health:z.enum(["normal","warning","fault","critical"]).default("normal"),recordedAt:z.iso.datetime()});return schema.safeParse(value)}
router.use(authenticate,requireModule("integration-lab"),managers);
router.get("/overview",asyncHandler(async(req,res)=>{const [profiles,gps,iot]=await Promise.all([getPool().query(`SELECT * FROM provider_adapters WHERE organization_id=$1 ORDER BY adapter_type,name`,[req.user.organization_id]),getPool().query(`SELECT d.id,d.device_uid,d.provider,d.last_seen_at,v.plate_number FROM gps_devices d JOIN fleet_vehicles v ON v.organization_id=d.organization_id AND v.id=d.vehicle_id WHERE d.organization_id=$1 ORDER BY d.created_at DESC`,[req.user.organization_id]),getPool().query(`SELECT id,device_uid,name,protocol,last_seen_at FROM iot_devices WHERE organization_id=$1 ORDER BY created_at DESC`,[req.user.organization_id])]);res.json({profiles:profiles.rows,gpsDevices:gps.rows,iotDevices:iot.rows,canonicalFields:canonical})}));
router.post("/profiles",asyncHandler(async(req,res)=>{const parsed=z.object({adapterType:z.enum(["gps","iot"]),code:z.string().trim().regex(/^[a-z0-9-]{2,50}$/),name:z.string().trim().min(2).max(150),mapping:z.record(z.string(),z.string()).default({}),samplePayload:z.record(z.string(),z.unknown()).default({})}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Adapter profile-ийн мэдээлэл буруу байна"});const v=parsed.data,allowed=new Set(canonical[v.adapterType]);if(Object.keys(v.mapping).some(x=>!allowed.has(x)))return res.status(400).json({error:"Танигдаагүй canonical field байна"});const result=await getPool().query(`INSERT INTO provider_adapters(organization_id,adapter_type,code,name,mapping,sample_payload,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[req.user.organization_id,v.adapterType,v.code,v.name,v.mapping,v.samplePayload,req.user.id]);await writeAudit(req,"integration.adapter_create","provider_adapter",result.rows[0].id,{type:v.adapterType,code:v.code});res.status(201).json({item:result.rows[0]})}));
router.post("/profiles/:id/test",asyncHandler(async(req,res)=>{const id=uuid.safeParse(req.params.id);if(!id.success)return res.status(400).json({error:"Adapter буруу байна"});const result=await getPool().query(`SELECT * FROM provider_adapters WHERE organization_id=$1 AND id=$2 AND active=true`,[req.user.organization_id,id.data]);if(!result.rowCount)return res.status(404).json({error:"Adapter олдсонгүй"});const p=result.rows[0],payload=req.body&&Object.keys(req.body).length?req.body:p.sample_payload,normalized=mapPayload(payload,p.mapping,p.adapter_type),checked=validate(p.adapter_type,normalized);res.json({valid:checked.success,normalized,issues:checked.success?[]:checked.error.issues.map(x=>({path:x.path.join("."),message:x.message})),targetEndpoint:p.adapter_type==="gps"?"POST /api/gps/ingest":"POST /api/iot/ingest"})}));
module.exports=router;
