"use strict";
const express=require("express");
const crypto=require("node:crypto");
const {rateLimit}=require("express-rate-limit");
const {z}=require("zod");
const {getPool}=require("../db");
const {authenticate,requireRoles,requireModule}=require("../middleware/auth");
const {writeAudit,writeDeviceAudit}=require("../services/audit");
const {PRIORITY_ORDER,priorityLevel,canIssuePriority}=require("../services/iot-priority");
const {emitAutomationEvent}=require("../services/automation");
const {asyncHandler}=require("../utils/async-handler");
const router=express.Router(),uuid=z.string().uuid(),hash=value=>crypto.createHash("sha256").update(value).digest("hex");
const managers=requireRoles("director","chief_engineer");
const controllers=requireRoles("director","chief_engineer","engineer","electric","camera_engineer");
const deviceLimiter=rateLimit({windowMs:60_000,limit:3000,standardHeaders:true,legacyHeaders:false});
const telemetrySchema=z.object({state:z.string().trim().min(1).max(80).default("unknown"),health:z.enum(["normal","warning","fault","critical"]).default("normal"),voltage:z.coerce.number().nullable().optional(),currentAmp:z.coerce.number().nullable().optional(),powerWatt:z.coerce.number().nullable().optional(),energyKwh:z.coerce.number().min(0).nullable().optional(),temperatureC:z.coerce.number().min(-100).max(300).nullable().optional(),signalStrength:z.coerce.number().int().min(-200).max(100).nullable().optional(),sensors:z.record(z.string(),z.unknown()).default({}),recordedAt:z.iso.datetime(),firmwareVersion:z.string().trim().max(100).optional(),localPolicyVersion:z.string().trim().max(100).optional()});
async function deviceFromKey(req){const key=String(req.headers["x-device-key"]||"");if(!/^iot_[a-f0-9]{64}$/.test(key))return null;const result=await getPool().query(`SELECT d.id,d.organization_id,d.device_uid FROM iot_devices d JOIN organizations o ON o.id=d.organization_id JOIN subscriptions s ON s.organization_id=o.id JOIN organization_modules om ON om.organization_id=o.id AND om.module_code='iot' AND om.enabled=true WHERE d.api_key_hash=$1 AND d.active=true AND o.status='active' AND s.status IN('trial','active','past_due')`,[hash(key)]);return result.rows[0]||null}

router.post("/ingest",deviceLimiter,asyncHandler(async(req,res)=>{const device=await deviceFromKey(req);if(!device)return res.status(401).json({error:"Device unavailable"});const parsed=telemetrySchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Invalid telemetry",issues:parsed.error.issues});const v=parsed.data,client=await getPool().connect();let telemetry;try{await client.query("BEGIN");const previous=await client.query(`SELECT state,health FROM iot_telemetry WHERE organization_id=$1 AND device_id=$2 ORDER BY recorded_at DESC LIMIT 1`,[device.organization_id,device.id]);const result=await client.query(`INSERT INTO iot_telemetry(organization_id,device_id,state,health,voltage,current_amp,power_watt,energy_kwh,temperature_c,signal_strength,sensors,recorded_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12) RETURNING id,received_at`,[device.organization_id,device.id,v.state,v.health,v.voltage??null,v.currentAmp??null,v.powerWatt??null,v.energyKwh??null,v.temperatureC??null,v.signalStrength??null,JSON.stringify(v.sensors),v.recordedAt]);telemetry=result.rows[0];await client.query(`UPDATE iot_devices SET last_seen_at=now(),firmware_version=COALESCE($2,firmware_version),local_policy_version=COALESCE($3,local_policy_version),updated_at=now() WHERE id=$1`,[device.id,v.firmwareVersion,v.localPolicyVersion]);const old=previous.rows[0];if(!old||old.state!==v.state||old.health!==v.health)await writeDeviceAudit(client,device,"iot.state_change","iot_device",device.id,{previousState:old?.state||null,state:v.state,previousHealth:old?.health||null,health:v.health,telemetryId:telemetry.id});await client.query("COMMIT");}catch(error){await client.query("ROLLBACK").catch(()=>{});throw error}finally{client.release()}if(v.health!=="normal")await emitAutomationEvent({organizationId:device.organization_id,eventType:"iot.telemetry.alert",payload:{deviceUid:device.device_uid,health:v.health,state:v.state,temperatureC:v.temperatureC,powerWatt:v.powerWatt},sourceEntityType:"iot_device",sourceEntityId:device.id,sourceDeliveryKey:`iot-telemetry:${device.id}:${v.recordedAt}`}).catch(error=>console.error("[automation]",error));res.status(202).json({ok:true,telemetryId:telemetry.id,receivedAt:telemetry.received_at})}));

router.get("/device/policy",deviceLimiter,asyncHandler(async(req,res)=>{const device=await deviceFromKey(req);if(!device)return res.status(401).json({error:"Device unavailable"});const result=await getPool().query(`SELECT version,rules,fail_safe,checksum,valid_from FROM iot_device_policies WHERE organization_id=$1 AND device_id=$2 AND active=true AND valid_from<=now() ORDER BY valid_from DESC,created_at DESC LIMIT 1`,[device.organization_id,device.id]);res.set("Cache-Control","no-store");res.json({policy:result.rows[0]||null,priorityOrder:PRIORITY_ORDER,keepLastValidWhenOffline:true})}));

router.get("/device/commands",deviceLimiter,asyncHandler(async(req,res)=>{const device=await deviceFromKey(req);if(!device)return res.status(401).json({error:"Device unavailable"});const client=await getPool().connect();try{await client.query("BEGIN");await client.query(`UPDATE iot_commands SET status='expired' WHERE organization_id=$1 AND device_id=$2 AND status IN('queued','delivered') AND expires_at<=now()`,[device.organization_id,device.id]);const result=await client.query(`SELECT id,action,payload,priority,priority_level,requested_at,expires_at FROM iot_commands WHERE organization_id=$1 AND device_id=$2 AND status='queued' AND expires_at>now() ORDER BY priority_level DESC,requested_at ASC LIMIT 20 FOR UPDATE`,[device.organization_id,device.id]);if(result.rowCount)await client.query(`UPDATE iot_commands SET status='delivered',delivered_at=now() WHERE organization_id=$1 AND id=ANY($2::uuid[])`,[device.organization_id,result.rows.map(x=>x.id)]);await client.query(`UPDATE iot_devices SET last_seen_at=now(),updated_at=now() WHERE id=$1`,[device.id]);await client.query("COMMIT");res.json({items:result.rows,priorityOrder:["emergency","manual","weather","schedule","default"]});}catch(error){await client.query("ROLLBACK").catch(()=>{});throw error}finally{client.release()}}));

router.post("/device/commands/:id/ack",deviceLimiter,asyncHandler(async(req,res)=>{const device=await deviceFromKey(req),id=uuid.safeParse(req.params.id),parsed=z.object({success:z.boolean(),result:z.record(z.string(),z.unknown()).default({}),errorMessage:z.string().trim().max(1000).default("")}).safeParse(req.body);if(!device)return res.status(401).json({error:"Device unavailable"});if(!id.success||!parsed.success)return res.status(400).json({error:"Invalid acknowledgement"});const client=await getPool().connect();try{await client.query("BEGIN");const result=await client.query(`UPDATE iot_commands SET status=$4,acknowledged_at=now(),result=$5::jsonb,error_message=$6 WHERE organization_id=$1 AND device_id=$2 AND id=$3 AND status IN('delivered','queued') RETURNING id,status,action,priority`,[device.organization_id,device.id,id.data,parsed.data.success?"acknowledged":"failed",JSON.stringify(parsed.data.result),parsed.data.errorMessage]);if(!result.rowCount){await client.query("ROLLBACK");return res.status(404).json({error:"Command unavailable"})}await writeDeviceAudit(client,device,"iot.command_ack","iot_command",id.data,{status:result.rows[0].status,action:result.rows[0].action,priority:result.rows[0].priority});await client.query("COMMIT");res.json({ok:true,item:result.rows[0]})}catch(error){await client.query("ROLLBACK").catch(()=>{});throw error}finally{client.release()}}));

router.use(authenticate,requireModule("iot"));
router.get("/overview",asyncHandler(async(req,res)=>{const org=req.user.organization_id;const [devices,commands]=await Promise.all([getPool().query(`SELECT d.id,d.asset_id,d.map_feature_id,d.device_uid,d.name,d.device_type,d.protocol,d.latitude,d.longitude,d.active,d.last_seen_at,d.firmware_version,d.local_policy_version,(d.last_seen_at>now()-interval '5 minutes') AS online,a.code AS asset_code,a.name AS asset_name,t.state,t.health,t.voltage,t.current_amp,t.power_watt,t.energy_kwh,t.temperature_c,t.signal_strength,t.sensors,t.recorded_at,(SELECT count(*)::int FROM iot_commands c WHERE c.organization_id=d.organization_id AND c.device_id=d.id AND c.status IN('queued','delivered')) AS pending_commands FROM iot_devices d LEFT JOIN assets a ON a.organization_id=d.organization_id AND a.id=d.asset_id LEFT JOIN LATERAL(SELECT * FROM iot_telemetry t WHERE t.organization_id=d.organization_id AND t.device_id=d.id ORDER BY t.recorded_at DESC LIMIT 1)t ON true WHERE d.organization_id=$1 ORDER BY d.active DESC,d.name`,[org]),getPool().query(`SELECT c.id,c.device_id,c.action,c.payload,c.priority,c.status,c.requested_at,c.delivered_at,c.acknowledged_at,c.expires_at,c.result,c.error_message,d.name AS device_name,u.full_name AS requested_by_name FROM iot_commands c JOIN iot_devices d ON d.organization_id=c.organization_id AND d.id=c.device_id LEFT JOIN users u ON u.organization_id=c.organization_id AND u.id=c.requested_by WHERE c.organization_id=$1 ORDER BY c.requested_at DESC LIMIT 200`,[org])]);res.json({devices:devices.rows,commands:commands.rows,priorityOrder:PRIORITY_ORDER});}));

router.post("/devices",managers,asyncHandler(async(req,res)=>{const parsed=z.object({deviceUid:z.string().trim().min(3).max(120),name:z.string().trim().min(2).max(200),deviceType:z.enum(["lighting","pump","energy","temperature","door","smoke","camera","other"]),protocol:z.enum(["http","mqtt","modbus-gateway","lorawan","other"]).default("http"),assetId:uuid.nullable().optional(),mapFeatureId:uuid.nullable().optional(),latitude:z.coerce.number().min(-90).max(90).nullable().optional(),longitude:z.coerce.number().min(-180).max(180).nullable().optional()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"IoT төхөөрөмжийн мэдээлэл буруу байна"});const v=parsed.data,key=`iot_${crypto.randomBytes(32).toString("hex")}`;const result=await getPool().query(`INSERT INTO iot_devices(organization_id,asset_id,map_feature_id,device_uid,name,device_type,protocol,api_key_hash,latitude,longitude,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,device_uid,name,device_type,protocol,latitude,longitude,active,created_at`,[req.user.organization_id,v.assetId||null,v.mapFeatureId||null,v.deviceUid,v.name,v.deviceType,v.protocol,hash(key),v.latitude??null,v.longitude??null,req.user.id]);await writeAudit(req,"iot.device_create","iot_device",result.rows[0].id,{deviceUid:v.deviceUid,name:v.name,type:v.deviceType});res.status(201).json({item:result.rows[0],apiKey:key,warning:"API key дахин харагдахгүй."});}));

router.post("/devices/:id/policies",managers,asyncHandler(async(req,res)=>{const id=uuid.safeParse(req.params.id),parsed=z.object({version:z.string().trim().regex(/^[A-Za-z0-9._-]+$/).min(1).max(100),rules:z.record(z.string(),z.unknown()).default({}),failSafe:z.object({action:z.string().trim().min(1).max(100),payload:z.record(z.string(),z.unknown()).default({})}),validFrom:z.iso.datetime().optional()}).safeParse(req.body);if(!id.success||!parsed.success)return res.status(400).json({error:"Invalid offline policy"});const v=parsed.data,canonical=JSON.stringify({priorityOrder:PRIORITY_ORDER,rules:v.rules,failSafe:v.failSafe}),checksum=hash(canonical),client=await getPool().connect();try{await client.query("BEGIN");const device=await client.query(`SELECT id FROM iot_devices WHERE organization_id=$1 AND id=$2 AND active=true FOR UPDATE`,[req.user.organization_id,id.data]);if(!device.rowCount){await client.query("ROLLBACK");return res.status(404).json({error:"Төхөөрөмж олдсонгүй"})}await client.query(`UPDATE iot_device_policies SET active=false WHERE organization_id=$1 AND device_id=$2 AND active=true`,[req.user.organization_id,id.data]);const result=await client.query(`INSERT INTO iot_device_policies(organization_id,device_id,version,rules,fail_safe,checksum,valid_from,created_by) VALUES($1,$2,$3,$4::jsonb,$5::jsonb,$6,COALESCE($7::timestamptz,now()),$8) RETURNING id,version,rules,fail_safe,checksum,valid_from,created_at`,[req.user.organization_id,id.data,v.version,JSON.stringify(v.rules),JSON.stringify(v.failSafe),checksum,v.validFrom||null,req.user.id]);await writeAudit(req,"iot.policy_change","iot_device",id.data,{policyId:result.rows[0].id,version:v.version,checksum},client);await client.query("COMMIT");res.status(201).json({item:result.rows[0],priorityOrder:PRIORITY_ORDER,offlineRule:"keep-last-valid"})}catch(error){await client.query("ROLLBACK").catch(()=>{});throw error}finally{client.release()}}));

router.post("/devices/:id/commands",controllers,asyncHandler(async(req,res)=>{const id=uuid.safeParse(req.params.id),parsed=z.object({action:z.string().trim().min(1).max(100),payload:z.record(z.string(),z.unknown()).default({}),priority:z.enum(PRIORITY_ORDER).default("manual"),expiresInSeconds:z.coerce.number().int().min(30).max(86400).default(900),idempotencyKey:z.string().trim().min(8).max(120).nullable().optional()}).safeParse(req.body);if(!id.success||!parsed.success)return res.status(400).json({error:"Command мэдээлэл буруу байна"});const v=parsed.data;if(!canIssuePriority(req.user.role,v.priority))return res.status(403).json({error:"This command priority is not authorized for the current role"});const level=priorityLevel(v.priority),client=await getPool().connect();try{await client.query("BEGIN");const device=await client.query(`SELECT id FROM iot_devices WHERE organization_id=$1 AND id=$2 AND active=true FOR UPDATE`,[req.user.organization_id,id.data]);if(!device.rowCount){await client.query("ROLLBACK");return res.status(404).json({error:"Төхөөрөмж олдсонгүй"})}const blocker=await client.query(`SELECT priority,priority_level FROM iot_commands WHERE organization_id=$1 AND device_id=$2 AND status IN('queued','delivered') AND expires_at>now() AND priority_level>$3 ORDER BY priority_level DESC LIMIT 1`,[req.user.organization_id,id.data,level]);if(blocker.rowCount){await client.query("ROLLBACK");return res.status(409).json({error:`${blocker.rows[0].priority} priority command идэвхтэй тул энэ command хүлээгдсэнгүй`})}const superseded=await client.query(`UPDATE iot_commands SET status='superseded' WHERE organization_id=$1 AND device_id=$2 AND status='queued' AND expires_at>now() AND priority_level<$3 RETURNING id,priority,action`,[req.user.organization_id,id.data,level]);const result=await client.query(`INSERT INTO iot_commands(organization_id,device_id,action,payload,priority,priority_level,requested_by,expires_at,idempotency_key) VALUES($1,$2,$3,$4::jsonb,$5,$6,$7,now()+($8::text||' seconds')::interval,$9) RETURNING *`,[req.user.organization_id,id.data,v.action,JSON.stringify(v.payload),v.priority,level,req.user.id,v.expiresInSeconds,v.idempotencyKey||null]);const action=v.priority==="emergency"?"iot.command_emergency":v.priority==="manual"?"iot.command_manual":"iot.command";await writeAudit(req,action,"iot_device",id.data,{commandId:result.rows[0].id,commandAction:v.action,priority:v.priority,superseded:superseded.rows},client);await client.query("COMMIT");res.status(201).json({item:result.rows[0]});}catch(error){await client.query("ROLLBACK").catch(()=>{});throw error}finally{client.release()}}));

module.exports=router;
